"""
AML23703 Quantum Computing -- Tutorial 4, Exercise 4  [REAL-WORLD]
=================================================================
Task : Emulate a classical full-adder circuit using Toffoli and CNOT gates.

Approach
--------
A full adder takes A, B and a carry-in and produces a sum bit and a
carry-out. The classical version uses AND and XOR, neither of which is
reversible, so both are rebuilt here: XOR becomes a CNOT, and AND becomes a
Toffoli writing onto a spare qubit. The circuit is then run for all eight
input combinations and each result is checked against ordinary Python
arithmetic, so the adder is verified rather than merely demonstrated.

Qubit map : q0 = A, q1 = B, q2 = Cin, q3 = Cout (ancilla, starts at |0>).
            After the circuit runs, the sum bit sits in q2 and the
            carry-out in q3.
"""

from itertools import product

import matplotlib.pyplot as plt
from qiskit import ClassicalRegister, QuantumCircuit, QuantumRegister, transpile
from qiskit_aer import AerSimulator

SHOTS = 256
A, B, CIN, COUT = 0, 1, 2, 3


def full_adder(a_bit, b_bit, cin_bit):
    """Build a full adder for one fixed input triple, with measurements."""
    q = QuantumRegister(4, "q")
    c = ClassicalRegister(2, "out")          # out[0] = sum, out[1] = carry
    qc = QuantumCircuit(q, c)

    # -- load the classical inputs -------------------------------------
    for bit, wire in ((a_bit, A), (b_bit, B), (cin_bit, CIN)):
        if bit:
            qc.x(wire)
    qc.barrier(label="inputs")

    # -- the adder itself ----------------------------------------------
    qc.ccx(A, B, COUT)       # carry generated by A AND B
    qc.cx(A, B)              # q1 now holds A XOR B
    qc.ccx(B, CIN, COUT)     # carry generated by (A XOR B) AND Cin
    qc.cx(B, CIN)            # q2 now holds A XOR B XOR Cin = sum
    qc.barrier(label="adder")

    qc.measure(CIN, 0)       # sum
    qc.measure(COUT, 1)      # carry-out
    return qc

# ---------------------------------------------------------------------
# 1. Show one representative circuit (the 1 + 1 + 1 case)
# ---------------------------------------------------------------------
example = full_adder(1, 1, 1)
print("--- Circuit Diagram (A=1, B=1, Cin=1) ---")
print(example.draw(output="text"))

print(f"\n  Gate count (as written)  : {dict(example.count_ops())}")
print(f"  Circuit depth            : {example.depth()}")
decomposed = transpile(example, basis_gates=["cx", "u"], optimization_level=0)
print(f"  Depth after decomposing into 1- and 2-qubit gates : {decomposed.depth()}")
print(f"  CNOTs after decomposition : {decomposed.count_ops().get('cx', 0)}")
print("  Each Toffoli is not a hardware gate; it is compiled into 6 CNOTs plus")
print("  single-qubit rotations, which is why the real depth is much larger.")

# ---------------------------------------------------------------------
# 2. Run all eight input combinations
# ---------------------------------------------------------------------
simulator = AerSimulator()
print(f"\n--- Full adder truth table ({SHOTS} shots per input) ---")
print("   A  B  Cin |  Sum  Cout  |  Expected  |  Deterministic  Correct")

all_correct = True
for a_bit, b_bit, cin_bit in product((0, 1), repeat=3):
    qc = full_adder(a_bit, b_bit, cin_bit)
    job = simulator.run(transpile(qc, simulator), shots=SHOTS)
    counts = job.result().get_counts()

    outcome = max(counts, key=counts.get)      # bitstring reads as "carry sum"
    carry, total = int(outcome[0]), int(outcome[1])

    classical = a_bit + b_bit + cin_bit
    expected_sum, expected_carry = classical % 2, classical // 2

    deterministic = len(counts) == 1
    correct = deterministic and total == expected_sum and carry == expected_carry
    all_correct &= correct

    print(f"   {a_bit}  {b_bit}   {cin_bit}  |   {total}    {carry}   |"
          f"   {expected_carry}{expected_sum} = {classical}  |"
          f"      {str(deterministic):5s}      {correct}")

print(f"\n  All eight rows correct : {all_correct}")
print("  Every run landed on a single outcome with no spread, which is what a")
print("  reversible circuit on basis-state inputs should do -- no superposition")
print("  was created anywhere, so there is nothing for the measurement to sample.")

# ---------------------------------------------------------------------
# 3. Why bother, if a classical adder already exists
# ---------------------------------------------------------------------
print("\n--- Note ---")
print("  On basis-state inputs this is only a slower classical adder. Its value")
print("  is that being reversible, it also runs on superposed inputs: feeding A")
print("  and B as superpositions adds every pair of numbers in one pass, which is")
print("  how arithmetic appears inside Shor's algorithm.")

# ---------------------------------------------------------------------
# 4. Circuit diagram figure
# ---------------------------------------------------------------------
example.draw(output="mpl", fold=-1)
plt.show()
